#!/usr/bin/env bash
#Write a Bash script that displays listening ports

echo "Active Internet connections (only servers)"
netstat -tuln -p
echo "Active UNIX domain sockets (only servers)"
netstat -xl -p

