#!/usr/bin/env bash
#Bash script that configures an Ubuntu server

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Set the IP addresses
localhost_ip="127.0.0.2"
facebook_ip="8.8.8.8"

# Use sed to edit the hosts file and add entries to map localhost and facebook.com to the specified IP addresses
sed -i "s/127.0.0.1/$new_localhost_ip/g" /etc/hosts
sed -i "s/102.132.101.35/$new_facebook_i/g" /etc/hosts
