#!/usr/bin/env bash
#Bash script that configures an Ubuntu server

# if [[ $EUID -ne 0 ]]; then
#     echo "This script must be run as root"
#     exit 1
# fi

# cp /etc/hosts /etc/hosts.backup

# echo "127.0.0.2    localhost" >> /etc/hosts
# echo "8.8.8.8      facebook.com" >> /etc/hosts

localhost_ip="127.0.0.2"
facebook_ip="8.8.8.8"

sed -i "s/127.0.0.1/$new_localhost_ip/g" /etc/hosts
sed -i "s/102.132.101.35/$new_facebook_i/g" /etc/hosts
