#!/usr/bin/env bash
#Bash script that configures an Ubuntu server

localhost_ip="127.0.0.2"
facebook_ip="8.8.8.8"

sed -i "s/127.0.0.1/$new_localhost_ip/g" /etc/hosts
sed -i "s/102.132.101.35/$new_facebook_i/g" /etc/hosts
