#!/usr/bin/env bash
#Write a Bash script that displays all active IPv4 IPs on the machine it’s executed on.
ipv4_addresses=$(ip -4 addr show | grep inet | grep -v '127.0.0.1' | awk '{print $2}' | cut -d'/' -f1)

echo "$ipv4_addresses"